// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR5XmJrDhLSRjNwgBlW4w8A2Dk3QocHJU',
    appId: '1:617383598676:web:1540c497481e508a9cebc1',
    messagingSenderId: '617383598676',
    projectId: 'todo-c98e8',
    authDomain: 'todo-c98e8.firebaseapp.com',
    storageBucket: 'todo-c98e8.firebasestorage.app',
    measurementId: 'G-H0WTLG5YT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvsDOQysSG37eqgo7ouIExgPRtpB3LMSs',
    appId: '1:617383598676:android:50920b4fc16090309cebc1',
    messagingSenderId: '617383598676',
    projectId: 'todo-c98e8',
    storageBucket: 'todo-c98e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIYEEpbwiwqxY8bCo5lkyIDbF0FhDh4CQ',
    appId: '1:617383598676:ios:51b23b02aed3bdcb9cebc1',
    messagingSenderId: '617383598676',
    projectId: 'todo-c98e8',
    storageBucket: 'todo-c98e8.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIYEEpbwiwqxY8bCo5lkyIDbF0FhDh4CQ',
    appId: '1:617383598676:ios:51b23b02aed3bdcb9cebc1',
    messagingSenderId: '617383598676',
    projectId: 'todo-c98e8',
    storageBucket: 'todo-c98e8.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR5XmJrDhLSRjNwgBlW4w8A2Dk3QocHJU',
    appId: '1:617383598676:web:0394a32258aa9c3c9cebc1',
    messagingSenderId: '617383598676',
    projectId: 'todo-c98e8',
    authDomain: 'todo-c98e8.firebaseapp.com',
    storageBucket: 'todo-c98e8.firebasestorage.app',
    measurementId: 'G-H6Q7SF3BL9',
  );
}
