name: Flutter CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.x

    - name: Install dependencies
      run: flutter pub get

    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Run tests
      id: run-tests
      run: |
        flutter test > test_output.txt
        cat test_output.txt
        echo "::set-output name=test_output::$(cat test_output.txt)"

    - name: Build release
      run: flutter build apk --release

    - name: Upload release build
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: testers
        file: build/app/outputs/flutter-apk/app-release.apk

    - name: Send Slack notification
      if: always()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "channel": "#todoflutter",
            "username": "github-actions",
            "text": "Test run completed for ${{ github.repository }}. Status: ${{ job.status }}\n\nTest Results:\n```${{ steps.run-tests.outputs.test_output }}```",
            "icon_emoji": ":octocat:"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}