name: Flutter CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.x

    - name: Install dependencies
      run: flutter pub get

    - name: Run build_runner
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Run tests
      run: flutter test